### ISSUE TITLE
unsupported method 'current_database'

### ISSUE THREAD

**Issue by grobie** [tcurdt/master_slave_adapter#4]
```
You called the unsupported method 'current_database' on ActiveRecord::ConnectionAdapters::MasterSlaveAdapter.
            In order to help us improve master_slave_adapter, please report this
            to: https://github.com/soundcloud/master_slave_adapter/issues

            Thank you.
```

During migration with [LargeHadronMigrator](https://github.com/soundcloud/large-hadron-migrator). Call is at [lib/large_hadron_migration.rb#L242](https://github.com/soundcloud/large-hadron-migrator/blob/master/lib/large_hadron_migration.rb#L242). `#current_database` is only implemented in [mysql adapter](https://github.com/rails/rails/blob/v2.3.9/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb#L424-426) and Postgresql adapter, but not in abstract adapter.

**Comment by kim** [comment]
fixed in v0.1.4 (soundcloud flavor ;))
